import chalk from "chalk";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import vm from "node:vm";
import ts from "typescript";

const FORBIDDEN_IMPORT_PATTERNS = [
  /from\s+["'](?:node:)?fs["']/,
  /from\s+["'](?:node:)?child_process["']/,
  /from\s+["'](?:node:)?net["']/,
  /from\s+["'](?:node:)?tls["']/,
  /from\s+["'](?:node:)?dns["']/,
  /require\(\s*["'](?:node:)?fs["']\s*\)/,
  /require\(\s*["'](?:node:)?child_process["']\s*\)/,
];

const STUDIO_ONLY_RULES: Array<{ pattern: RegExp; message: string }> = [
  { pattern: /\bfetch\s*\(/, message: "Use ctx.web.read/write instead of raw fetch." },
  {
    pattern: /\bauth\.getClient\s*\(/,
    message: "Use ctx.integration(...) instead of auth.getClient(...).",
  },
  {
    pattern: /\bauth\.getToken\s*\(/,
    message: "Use ctx.integration(...) helpers instead of auth.getToken(...).",
  },
  {
    pattern: /\bprocess\.env\b/,
    message: "Generated workflows must not read process.env directly.",
  },
  {
    pattern: /\baxios\b/,
    message: "Use WorkflowContext helpers instead of axios.",
  },
];

function detectMode(source: string): "studio" | "legacy" {
  return source.includes("Generated by GTMShip Workflow Studio")
    ? "studio"
    : "legacy";
}

function compileSource(source: string, fileName: string) {
  return ts.transpileModule(source, {
    fileName,
    reportDiagnostics: true,
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.CommonJS,
      esModuleInterop: true,
      strict: true,
    },
  });
}

function loadWorkflowDefinition(source: string, fileName: string) {
  const compiled = compileSource(source, fileName);
  const diagnostics = (compiled.diagnostics || []).map((diagnostic) =>
    ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n")
  );

  if (diagnostics.length > 0) {
    throw new Error(diagnostics.join("\n"));
  }

  const module = { exports: {} as Record<string, unknown> };
  const sandbox = {
    module,
    exports: module.exports,
    require(specifier: string) {
      if (specifier === "@gtmship/sdk") {
        return {
          defineWorkflow<T>(config: T): T {
            return config;
          },
          triggers: {
            manual() {
              return { type: "manual" };
            },
            webhook(path: string) {
              return { type: "webhook", path };
            },
            schedule(cron: string) {
              return { type: "schedule", cron };
            },
            event(eventName: string) {
              return { type: "event", event: eventName };
            },
          },
          auth: {
            getClient() {
              throw new Error("auth.getClient() unavailable in validate mode");
            },
            getToken() {
              throw new Error("auth.getToken() unavailable in validate mode");
            },
          },
        };
      }

      throw new Error(`Unsupported import in workflow: ${specifier}`);
    },
    console,
    Buffer,
    URL,
    fetch,
    process: { env: {} },
  };

  vm.runInNewContext(compiled.outputText, sandbox, {
    filename: fileName,
    timeout: 2_000,
  });

  return module.exports.default || module.exports;
}

function detectWriteCheckpoints(source: string): string[] {
  return Array.from(
    source.matchAll(/checkpoint\s*:\s*["'`]([^"'`]+)["'`]/g)
  ).map((match) => match[1]);
}

function missingCheckpointErrors(source: string): string[] {
  return Array.from(source.matchAll(/\.write\s*\(\s*[\s\S]*?\)/g))
    .map((match) => match[0])
    .filter((snippet) => !/checkpoint\s*:/.test(snippet))
    .map(() => "Every ctx.*.write(...) call must include a checkpoint.");
}

function printIssue(
  fileName: string,
  level: "error" | "warning",
  message: string
) {
  const color = level === "error" ? chalk.red : chalk.yellow;
  const marker = level === "error" ? "✗" : "⚠";
  console.log(color(`  ${marker} ${fileName}: ${message}`));
}

export async function validateCommand() {
  console.log(chalk.blue("\n🔍 Validating GTMShip project...\n"));

  let errors = 0;
  let warnings = 0;

  const configPath = join(process.cwd(), "gtmship.config.yaml");
  if (!existsSync(configPath)) {
    console.log(chalk.red("  ✗ gtmship.config.yaml not found"));
    console.log(chalk.gray("    Run 'gtmship init' to create a project"));
    process.exit(1);
  }
  console.log(chalk.green("  ✓ gtmship.config.yaml found"));

  const workflowsDir = join(process.cwd(), "workflows");
  if (!existsSync(workflowsDir)) {
    console.log(chalk.yellow("  ⚠ No workflows/ directory found"));
    warnings++;
  } else {
    const workflows = readdirSync(workflowsDir).filter((file) =>
      file.endsWith(".ts") || file.endsWith(".js")
    );

    if (workflows.length === 0) {
      console.log(chalk.yellow("  ⚠ No workflow files found"));
      warnings++;
    } else {
      console.log(chalk.green(`  ✓ Found ${workflows.length} workflow(s)`));

      for (const workflowFile of workflows) {
        const workflowPath = join(workflowsDir, workflowFile);
        const metadataPath = join(
          process.cwd(),
          ".gtmship",
          "workflows",
          workflowFile.replace(/\.(ts|js)$/, ".json")
        );
        const source = readFileSync(workflowPath, "utf8");
        const mode = detectMode(source);
        const compile = compileSource(source, workflowFile);
        const compileDiagnostics = (compile.diagnostics || []).map((diagnostic) =>
          ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n")
        );

        if (compileDiagnostics.length === 0) {
          console.log(chalk.gray(`    - ${workflowFile} (${mode})`));
        } else {
          for (const diagnostic of compileDiagnostics) {
            printIssue(workflowFile, "error", diagnostic);
            errors++;
          }
        }

        for (const pattern of FORBIDDEN_IMPORT_PATTERNS) {
          if (pattern.test(source)) {
            printIssue(
              workflowFile,
              "error",
              `Forbidden module usage detected: ${pattern}`
            );
            errors++;
          }
        }

        if (mode === "studio") {
          for (const rule of STUDIO_ONLY_RULES) {
            if (rule.pattern.test(source)) {
              printIssue(workflowFile, "error", rule.message);
              errors++;
            }
          }

          for (const message of missingCheckpointErrors(source)) {
            printIssue(workflowFile, "error", message);
            errors++;
          }
        }

        try {
          const workflow = loadWorkflowDefinition(source, workflowFile) as {
            id?: string;
            trigger?: { type?: string };
            run?: unknown;
          };

          if (!workflow || typeof workflow !== "object") {
            printIssue(
              workflowFile,
              "error",
              "Workflow must export a default defineWorkflow(...) object."
            );
            errors++;
          } else {
            if (!workflow.id) {
              printIssue(workflowFile, "error", "Workflow id is required.");
              errors++;
            }
            if (!workflow.trigger?.type) {
              printIssue(workflowFile, "error", "Workflow trigger is required.");
              errors++;
            }
            if (typeof workflow.run !== "function") {
              printIssue(workflowFile, "error", "Workflow run function is required.");
              errors++;
            }
          }
        } catch (error) {
          printIssue(
            workflowFile,
            "error",
            error instanceof Error ? error.message : "Failed to evaluate workflow."
          );
          errors++;
        }

        if (existsSync(metadataPath)) {
          try {
            const metadata = JSON.parse(readFileSync(metadataPath, "utf8")) as {
              artifact?: { writeCheckpoints?: Array<{ id: string }> };
            };
            const detected = detectWriteCheckpoints(source);
            for (const checkpoint of metadata.artifact?.writeCheckpoints || []) {
              if (!detected.includes(checkpoint.id)) {
                printIssue(
                  workflowFile,
                  "error",
                  `Write checkpoint "${checkpoint.id}" is declared in metadata but missing in code.`
                );
                errors++;
              }
            }
          } catch (error) {
            printIssue(
              workflowFile,
              "warning",
              error instanceof Error
                ? `Failed to parse sidecar metadata: ${error.message}`
                : "Failed to parse sidecar metadata."
            );
            warnings++;
          }
        } else if (mode === "studio") {
          printIssue(
            workflowFile,
            "warning",
            "Studio-generated workflow is missing its .gtmship sidecar metadata."
          );
          warnings++;
        }
      }
    }
  }

  const connectionsDir = join(process.cwd(), "connections");
  if (existsSync(connectionsDir)) {
    const configs = readdirSync(connectionsDir).filter(
      (file) => file.endsWith(".yaml") || file.endsWith(".json")
    );
    console.log(chalk.green(`  ✓ Found ${configs.length} connection config(s)`));
  }

  console.log("");
  if (errors > 0) {
    console.log(chalk.red(`  ${errors} error(s), ${warnings} warning(s)`));
    process.exit(1);
  } else if (warnings > 0) {
    console.log(chalk.yellow(`  ${warnings} warning(s), 0 errors`));
  } else {
    console.log(chalk.green("  ✓ All checks passed!"));
  }
}
