import type { WorkflowConfig } from "./types.js";

/**
 * Define a GTMShip workflow.
 *
 * This is the primary API for creating workflows that can be
 * generated by AI coding tools (Claude Code, Codex) and deployed
 * via `gtmship deploy`.
 *
 * @example
 * ```ts
 * import { defineWorkflow, triggers, auth } from "@gtmship/sdk";
 *
 * export default defineWorkflow({
 *   id: "enrich-lead",
 *   trigger: triggers.webhook("/enrich"),
 *   async run(payload: { email: string }) {
 *     const hubspot = await auth.getClient("hubspot");
 *     const result = await hubspot.get(`/contacts?email=${payload.email}`);
 *     return result.data;
 *   },
 * });
 * ```
 */
export function defineWorkflow<TPayload = unknown, TResult = unknown>(
  config: WorkflowConfig<TPayload, TResult>
): WorkflowConfig<TPayload, TResult> {
  if (!config.id) {
    throw new Error("Workflow must have an id");
  }
  if (!config.trigger) {
    throw new Error("Workflow must have a trigger");
  }
  if (!config.run) {
    throw new Error("Workflow must have a run function");
  }

  return config;
}
