import vm from "node:vm";
import ts from "typescript";

export interface CompiledWorkflowSource {
  outputText: string;
  diagnostics: string[];
}

export interface RuntimeSdkExports {
  defineWorkflow: <T>(config: T) => T;
  triggers: {
    manual: () => { type: "manual" };
    webhook: (
      path: string,
      options?: Record<string, unknown>
    ) => { type: "webhook"; path: string; config?: { webhook: Record<string, unknown> } };
    schedule: (
      cron: string,
      options?: Record<string, unknown>
    ) => { type: "schedule"; cron: string; config?: { schedule: Record<string, unknown> } };
    event: (
      eventName: string,
      options?: Record<string, unknown>
    ) => { type: "event"; event: string; config?: { event: Record<string, unknown> } };
  };
  auth?: Record<string, unknown>;
  createWorkflowContext?: (...args: unknown[]) => unknown;
}

export interface WorkflowRuntimeOptions {
  console?: typeof console;
  timeoutMs?: number;
}

interface WorkflowDefinitionWithId {
  id?: string;
}

function normalizeDiagnostic(
  diagnostic: ts.Diagnostic
): string {
  return ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n");
}

export function detectWorkflowMode(source: string): "studio" | "legacy" {
  return source.includes("Generated by GTMShip Workflow Studio")
    ? "studio"
    : "legacy";
}

export function compileWorkflowSource(
  source: string,
  fileName = "workflow.ts"
): CompiledWorkflowSource {
  const result = ts.transpileModule(source, {
    fileName,
    reportDiagnostics: true,
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.CommonJS,
      esModuleInterop: true,
      strict: true,
    },
  });

  return {
    outputText: result.outputText,
    diagnostics: (result.diagnostics || []).map(normalizeDiagnostic),
  };
}

export function loadWorkflowDefinitionFromSource<T>(
  source: string,
  sdkExports: RuntimeSdkExports,
  fileName = "workflow.ts",
  options?: WorkflowRuntimeOptions
): T {
  const compiled = compileWorkflowSource(source, fileName);

  if (compiled.diagnostics.length > 0) {
    throw new Error(compiled.diagnostics.join("\n"));
  }

  const module = { exports: {} as Record<string, unknown> };
  const sandbox = {
    module,
    exports: module.exports,
    require(specifier: string) {
      if (specifier === "@gtmship/sdk") {
        return sdkExports;
      }

      throw new Error(
        `Workflow Studio runtime blocks external module imports: ${specifier}`
      );
    },
    console: options?.console ?? console,
    Buffer,
    URL,
    fetch,
    setTimeout,
    clearTimeout,
    process: { env: {} },
  };

  vm.runInNewContext(compiled.outputText, sandbox, {
    filename: fileName,
    timeout: options?.timeoutMs ?? 2_000,
  });

  const exported =
    (module.exports.default as T | undefined) ||
    (module.exports as unknown as T);

  return exported;
}

function buildWorkflowDefinitionSdkStub(): RuntimeSdkExports {
  return {
    defineWorkflow<T>(config: T): T {
      return config;
    },
    triggers: {
      manual() {
        return { type: "manual" as const };
      },
      webhook(path: string, options?: Record<string, unknown>) {
        return {
          type: "webhook" as const,
          path,
          config:
            options && Object.keys(options).length > 0
              ? { webhook: options }
              : undefined,
        };
      },
      schedule(cronInput: string | { cron?: string }, options?: Record<string, unknown>) {
        const cron =
          typeof cronInput === "string"
            ? cronInput
            : typeof cronInput?.cron === "string"
              ? cronInput.cron
              : "";

        const scheduleOptions =
          typeof cronInput === "object" && cronInput !== null
            ? cronInput
            : options;

        return {
          type: "schedule" as const,
          cron,
          config:
            scheduleOptions && Object.keys(scheduleOptions).length > 0
              ? { schedule: scheduleOptions }
              : undefined,
        };
      },
      event(eventName: string, options?: Record<string, unknown>) {
        return {
          type: "event" as const,
          event: eventName,
          config:
            options && Object.keys(options).length > 0
              ? { event: options }
              : undefined,
        };
      },
    },
    auth: {},
    createWorkflowContext() {
      return {};
    },
  };
}

export function extractWorkflowIdFromSource(
  source: string,
  fallback: string,
  fileName = "workflow.ts"
): string {
  try {
    const definition = loadWorkflowDefinitionFromSource<WorkflowDefinitionWithId>(
      source,
      buildWorkflowDefinitionSdkStub(),
      fileName
    );
    const workflowId =
      typeof definition?.id === "string" ? definition.id.trim() : "";
    return workflowId || fallback;
  } catch {
    return fallback;
  }
}
