/**
 * Example GTMShip Workflow: Lead Enrichment
 *
 * This workflow receives a lead email via webhook,
 * looks up the contact in HubSpot, and enriches it.
 *
 * Generated by Claude Code / Codex against @gtmship/sdk
 */
import { defineWorkflow, triggers, auth } from "@gtmship/sdk";

export default defineWorkflow({
  id: "enrich-lead",
  name: "Lead Enrichment",
  description: "Enrich incoming leads with HubSpot contact data",
  trigger: triggers.webhook("/enrich"),

  async run(payload: { email: string; source?: string }) {
    // Get authenticated HubSpot client
    const hubspot = await auth.getClient("hubspot");

    // Search for existing contact
    const searchResponse = await hubspot.post(
      "/crm/v3/objects/contacts/search",
      {
        filterGroups: [
          {
            filters: [
              {
                propertyName: "email",
                operator: "EQ",
                value: payload.email,
              },
            ],
          },
        ],
      }
    );

    const contacts = searchResponse.data.results;

    if (contacts.length > 0) {
      const contact = contacts[0];
      return {
        status: "found",
        contact: {
          id: contact.id,
          email: payload.email,
          firstName: contact.properties.firstname,
          lastName: contact.properties.lastname,
          company: contact.properties.company,
          jobTitle: contact.properties.jobtitle,
        },
      };
    }

    // Create new contact if not found
    const createResponse = await hubspot.post("/crm/v3/objects/contacts", {
      properties: {
        email: payload.email,
        hs_lead_status: "NEW",
        lifecyclestage: "lead",
      },
    });

    return {
      status: "created",
      contactId: createResponse.data.id,
      email: payload.email,
    };
  },
});
